Stage()
Note(targetTime = 1.0, lane = 1)
Note(targetTime = 2.0, lane = 3)
Note(targetTime = 3.0, lane = 5)
Note(targetTime = 4.0, lane = 7)
Note(targetTime = 5.0, lane = 2)
Note(targetTime = 5.0, lane = 6)
Note(targetTime = 6.0, lane = 4)